---
name: "jellyfin-oidc"
guid: "9f6ee0ce-2057-49bf-be5f-c3fb31bff323"
version: "1.0.0.0"
targetAbi: "10.7.0.0"
framework: "net5.0"
overview: "Short description about your plugin"
description: >
  This is a longer description that can span more than one
  line and include details about your plugin.
category: "General"
owner: "jellyfin"
artifacts:
- "Jellyfin.Plugin.OIDC.dll"
changelog: >
  changelog
